# Exercise 2.A Fundamentals of pandas

In [2]:
import numpy as np
import pandas as pd

## Series

Start by creating four new variables named aa, ab, ac, and ad to hold some plain
Python objects

In [5]:
aa = [1, 2, 3, 4]
ab = (5, 6, 7, 8)
ac = {9, 10, 11, 12}
ad = {'first':13, 'second':14, 'third':15, 'fourth':16}

Create four new variables named ser1, ser2, ser3, and ser4. Assign to each a
Series created from one of the previous four variables

In [8]:
#had isses b/c s must be capitalized for Series (are class/type)

ser1 = pd.Series(aa)
print(ser1)
ser2 = pd.Series(ab)
print(ser2)
#ser3 = pd.Series(ac)# issues ac is set have to covnert to list first
ser3 = pd.Series(list(ac))
print(ser3)
ser4 = pd.Series(ad)
print(ser4)

0    1
1    2
2    3
3    4
dtype: int64
0    5
1    6
2    7
3    8
dtype: int64
0     9
1    10
2    11
3    12
dtype: int64
first     13
second    14
third     15
fourth    16
dtype: int64

In a new cell, create a variable named ser5 and assign it the literal values 17, 18,
19, 20. When you run the cell, what happens?

In [10]:
ser5 = 17, 18, 19, 20
print(ser5)
# no error code, just a tuple (17,18,19,20)
# as a pd.Series
ser5 = pd.Series([17, 18, 19, 20])
print(ser5)
#series worked as well out was index-values and datatype

(17, 18, 19, 20)
0    17
1    18
2    19
3    20
dtype: int64

## DataFrames from Series

Create new variable df1 and give it the value of a DataFrame using ser1. Then on
the next line, call df1 by simply typing in the variable name (no print function).
When you run the cell, a simple formatted DataFrame should be returned.

In [47]:
df1 = pd.DataFrame(ser1)
df1

   0
0  1
1  2
2  3
3  4

Add two new columns to df1 via the insert() method using ser2 and ser3 for each column. Call df1 to review the updated DataFrame.

In [48]:
df1.insert(1, 1, ser2)
#(position, column name, insert data)
df1.insert(2, 2, ser3)

df1

   0  1   2
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

Add a third new column to df1 using ser4. What happens this time when you call df1? Add a comment explaining the difference between ser4 compared to the other Series data used, and how this affected the outcome.

In [49]:
df1.insert(3, 3, ser4)
df1
#ser4 column had Nan (missing value), ser4 is a dictionary with key and values
#vs. the other ser just have integers

   0  1   2   3
0  1  5   9 NaN
1  2  6  10 NaN
2  3  7  11 NaN
3  4  8  12 NaN

Add a new row 4 using the loc attribute with the values 5, 9, 12, 0. Call df1 to review
the updated DataFrame.

In [50]:
df1.loc[4] = [5, 9, 12, 0]
df1

   0  1   2    3
0  1  5   9  NaN
1  2  6  10  NaN
2  3  7  11  NaN
3  4  8  12  NaN
4  5  9  12  0.0

## Reading data into a DataFrame.

Create a new variable df2. Use the read_csv function to read the contents of sakila_example.csv into df2. (Note that you will need to save the CSV file to the same folder where Jupyter Notebook is running for this exercise.) Call df2 to review the result.

In [7]:
df2 = pd.read_csv('sakila_example.csv')

df2

,title,description,category,language,actor_name
0,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,PENELOPE GUINESS
1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,CHRISTIAN GABLE
2,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,LUCILLE TRACY
3,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,SANDRA PECK
4,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,JOHNNY CAGE
...,...,...,...,...,...
257,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,GARY PENN
258,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,CHRISTOPHER WEST
259,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,DUSTIN TAUTOU
260,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,ANGELA HUDSON
261,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,JAMES PITT

Display the top 5 records from df2

In [9]:

print(df2.head())

              title                                        description  \
0  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...
1  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...
2  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...
3  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...
4  ACADEMY DINOSAUR  A Epic Drama of a Feminist And a Mad Scientist...

      category language        actor_name
0  Documentary  English  PENELOPE GUINESS
1  Documentary  English   CHRISTIAN GABLE
2  Documentary  English     LUCILLE TRACY
3  Documentary  English       SANDRA PECK
4  Documentary  English       JOHNNY CAGE

Display the last 10 records from df2.

In [10]:
print(df2.tail(10))

                 title                                        description  \
252       ATTACKS HATE  A Fast-Paced Panorama of a Technical Writer An...
253       ATTACKS HATE  A Fast-Paced Panorama of a Technical Writer An...
254       ATTACKS HATE  A Fast-Paced Panorama of a Technical Writer An...
255  ATTRACTION NEWTON  A Astounding Panorama of a Composer And a Fris...
256  ATTRACTION NEWTON  A Astounding Panorama of a Composer And a Fris...
257  ATTRACTION NEWTON  A Astounding Panorama of a Composer And a Fris...
258  ATTRACTION NEWTON  A Astounding Panorama of a Composer And a Fris...
259        AUTUMN CROW  A Beautiful Tale of a Dentist And a Mad Cow wh...
260        AUTUMN CROW  A Beautiful Tale of a Dentist And a Mad Cow wh...
261        AUTUMN CROW  A Beautiful Tale of a Dentist And a Mad Cow wh...

    category language        actor_name
252   Sci-Fi  English      MILLA KEITEL
253   Sci-Fi  English     GROUCHO DUNST
254   Sci-Fi  English       BURT TEMPLE
255      New  English          UMA WOOD
256      New  English       RIP WINSLET
257      New  English         GARY PENN
258      New  English  CHRISTOPHER WEST
259    Games  English     DUSTIN TAUTOU
260    Games  English     ANGELA HUDSON
261    Games  English        JAMES PITT

Show summary information about df2 using the info method

In [11]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        262 non-null    str
 1   description  262 non-null    str
 2   category     262 non-null    str
 3   language     262 non-null    str
 4   actor_name   262 non-null    str
dtypes: str(5)
memory usage: 10.4 KB

Add a markdown cell. Looking at the info results, what are a few facts you can determine about this data?

Looking at the result, I can see it shows the number of total columns (5), index, the name of columns, the dtype(str), memory usage(10.4kb), the class (pandas-DataFrame).

Show column statistics on df2 using the describe method.

In [12]:
df2.describe()

,title,description,category,language,actor_name
count,262,262,262,262,262
unique,46,46,15,1,145
top,ARABIA DOGMA,A Touching Epistle of a Madman And a Mad Cow w...,Horror,English,OPRAH KILMER
freq,12,12,55,262,8

Add a markdown cell. Looking at the describe results, what are the useful insights you can take away? What summarizations are likely not so useful?

It looks useful the results show a count for each column, the top(like mode) for each column, feq(most appeared value) of each column, unique(like distinct values).

Create a new variable df3. Use the read_csv function to read the contents of northwind_example.csv into df3. (Note again that you will need to save the CSV file
to the same folder where Jupyter Notebook is running for this exercise.) Call df3 to review the result

In [21]:
df3 = pd.read_csv('northwind_example.csv')

df3

     OrderID                    ProductName  UnitPrice  Quantity
0      10248                 Queso Cabrales       14.0        12
1      10248  Singaporean Hokkien Fried Mee        9.8        10
2      10248         Mozzarella di Giovanni       34.8         5
3      10249          Manjimup Dried Apples       42.4        40
4      10249                           Tofu       18.6         9
..       ...                            ...        ...       ...
495    10435         Mozzarella di Giovanni       27.8        10
496    10436         Gnocchi di nonna Alice       30.4        40
497    10436       Wimmers gute Semmelkndel       26.6        30
498    10436             Rhnbru Klosterbier        6.2        24
499    10436                      Spegesild        9.6         5

[500 rows x 4 columns]

Show column statistics on df3 using the describe method

In [22]:
df3.describe()

            OrderID   UnitPrice    Quantity
count    500.000000  500.000000  500.000000
mean   10341.364000   23.371400   24.330000
std       54.442663   27.334436   18.069702
min    10248.000000    2.000000    1.000000
25%    10294.000000   10.400000   10.000000
50%    10341.000000   15.800000   20.000000
75%    10389.000000   27.800000   32.000000
max    10436.000000  210.800000  120.000000

Looking at the describe results, what are the useful insights you can take away? How are the summarizations here different than for the previous example, and why?

The differnce from df2 to df3 is that df3 has percentages(.25,.50,.75), std, mean, and max. df3 has numeric values vs. df2 is string values

## Coding a DataFrame

Create a new variable named test_data and assign it a dictionary with the following key-value pairs:
'ID': [1, 2, 3, 4, 5, 6, 7, 8],
'Name': ['Alicia', 'Bob', 'Charlie', 'Dominic', 'Eve', 'Frank', 'Grace', 'Heidi'],
'Age': [25, np.nan, 22, 19, 31, 35, np.nan, 18],
'City': ['NY', 'LA', 'Chicago', 'Houston', 'Phoenix', 'Boston', 'Austin', 'San Diego'],
'Score': [85, 92, -1, 65, 78, np.nan, 55, 90]

In [24]:
test_data = {'ID': [1, 2, 3, 4, 5, 6, 7, 8],
'Name': ['Alicia', 'Bob', 'Charlie', 'Dominic', 'Eve', 'Frank', 'Grace', 'Heidi'],
'Age': [25, np.nan, 22, 19, 31, 35, np.nan, 18],
'City': ['NY', 'LA', 'Chicago', 'Houston', 'Phoenix', 'Boston', 'Austin', 'San Diego'],
'Score': [85, 92, -1, 65, 78, np.nan, 55, 90]}

Create a DataFrame named df4 using test_data. Call df4 to review the result

In [25]:
df4 = pd.DataFrame(test_data)
df4

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

Export df4 to a CSV file named test_data.csv

In [26]:
df4.to_csv('test_data.csv', index=False)